
platform :ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'

def import_pods
  pod 'web3swift'
end


target 'DID-SDK-Swift_Example' do
  
  use_frameworks!
  
  import_pods
  
  pod 'DID-SDK-Swift', :path => '../'

  target 'DID-SDK-Swift_Tests' do
    
    use_frameworks!
    
    inherit! :search_paths
    
    import_pods
    
  end
end
